# Generated by Django 5.2.7 on 2025-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WholesaleInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=255)),
                ("expected_monthly_units", models.PositiveIntegerField()),
                ("message", models.TextField()),
            ],
        ),
    ]
